/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdsbdbVue: typeof import('./src/components/Projects/AdsbdbVue.vue')['default']
    AHref: typeof import('./src/components/AHref.vue')['default']
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    AppDivider: typeof import('./src/components/AppDivider.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppSnackBar: typeof import('./src/components/AppSnackBar.vue')['default']
    AppUpArrow: typeof import('./src/components/AppUpArrow.vue')['default']
    BackendApi: typeof import('./src/components/BackendApi.vue')['default']
    BelugasnoozeClient: typeof import('./src/components/Projects/BelugasnoozeClient.vue')['default']
    BelugasnoozeSite: typeof import('./src/components/Projects/BelugasnoozeSite.vue')['default']
    CHref: typeof import('./src/components/CHref.vue')['default']
    CodeBlock: typeof import('./src/components/blog/CodeBlock.vue')['default']
    CompanionVue: typeof import('./src/components/CompanionVue.vue')['default']
    FrontendVue: typeof import('./src/components/FrontendVue.vue')['default']
    HavnVue: typeof import('./src/components/Projects/HavnVue.vue')['default']
    IHref: typeof import('./src/components/IHref.vue')['default']
    LeafcastPi: typeof import('./src/components/Projects/LeafcastPi.vue')['default']
    LeafcastSite: typeof import('./src/components/Projects/LeafcastSite.vue')['default']
    MealpedantApi: typeof import('./src/components/Projects/MealpedantApi.vue')['default']
    MealpedantSite: typeof import('./src/components/Projects/MealpedantSite.vue')['default']
    MrJackWills: typeof import('./src/components/Projects/MrJackWills.vue')['default']
    ObliqoroVue: typeof import('./src/components/Projects/ObliqoroVue.vue')['default']
    OxkerVue: typeof import('./src/components/Projects/OxkerVue.vue')['default']
    RedSpan: typeof import('./src/components/blog/RedSpan.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StaticpiBackend: typeof import('./src/components/Projects/StaticpiBackend.vue')['default']
    StaticpiVue: typeof import('./src/components/Projects/StaticpiVue.vue')['default']
    TSBranch: typeof import('./src/components/TSBranch.vue')['default']
    UpArrow: typeof import('./src/components/UpArrow.vue')['default']
    UppArrow: typeof import('./src/components/UppArrow.vue')['default']
    UseStaticPi: typeof import('./src/components/UseStaticPi.vue')['default']
  }
}
